original_prompt: "ok set Active Queries to 3 second delay instead of 10 and add a parameters to change this"

optimized_prompt: |
  Add configurable active query interval parameter to the BitTorrent DHT crawler.

  Requirements:
  1. Change default active query interval from 10 seconds to 3 seconds
  2. Add --query-interval command-line parameter to scraper.py
  3. Pass the parameter to DHTClient.crawl_network() method
  4. Update help text to explain the parameter
  5. Validate the parameter (must be positive integer >= 1)
  6. Maintain backward compatibility

  Technical changes:
  - Modify DHTClient.crawl_network() to accept query_interval parameter
  - Update scraper.py argument parser with --query-interval option
  - Change hardcoded `query_count % 10` to use configurable interval
  - Add input validation for the interval value

  Testing:
  - Write unit tests for interval validation
  - Update existing tests if needed
  - Verify all tests still pass

  Security:
  - Validate interval is positive integer
  - Prevent values that could DOS the network (too low)
  - Add reasonable minimum (e.g., 1 second)

date: 2025-10-24
context: "BitTorrent DHT Scraper - Active query interval configuration"
